site_name: LibreOffice Programming
# site_url: https://flywire.github.io/lo-p/
site_description: >-
  LibreOffice Programming (LO-P) is intended for programmers who want 
  to learn how to use the the LibreOffice API. This allows programs to control 
  and manipulate LibreOffice's text, drawing, presentation, spreadsheet, and 
  database applications, and a lot more (e.g. its spell checker, forms 
  designer, and charting tools).  

repo_name: lo-p
repo_url: https://github.com/flywire/lo-p

use_directory_urls: false

theme:
  name: material
  # custom_dir: docs/overrides
  palette:
    scheme: preference
  static_templates:
    - 404.html
  features:
    #- navigation.instant
    #- navigation.sections
    #- navigation.tabs
    #- header.autohide

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

  - pymdownx.magiclink


extra_css:
  - css/extra.css
    
plugins:
  - search